### ISSUE TITLE
Legacy binding issues

### ISSUE THREAD

**Issue by TongSericus** [SmoQySuite/StableLinearAlgebra.jl#6]
The internal API name for liblapack has changed in some lastest update, and in Windows it looks like
```julia
julia> LinearAlgebra.LAPACK.liblapack
"libblastrampoline-5.dll"
```
I would suggest changing the API binding in the module file (line 17) from
```julia
const liblapack = "libblastrampoline"
```
to
```julia
const liblapack = LinearAlgebra.LAPACK.liblapack
```

**Comment by cohensbw** [comment]
Thank you for pointing this out!
